#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: eclipse-repo-build
  namespace: galasa-tekton
spec:
  resources:
  - name: git-eclipse
    type: git
  params:
  - name: distBranch
    type: string
  - name: noPush
    type: string
    default: ""
  tasks:
  - name: eclipse-build
    taskRef:
      name: eclipse-repo-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: eclipseRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/photon/
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: noPush
      value: $(params.noPush)
    resources:
      inputs:
      - name: git-eclipse
        resource: git-eclipse
  - name: recycle-eclipse-maven
    taskRef:
      name: recycle-deployment
    runAfter:
    - eclipse-build
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-eclipse
  - name: recycle-eclipse-p2
    taskRef:
      name: recycle-deployment
    runAfter:
    - eclipse-build
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: p2-$(params.distBranch)
