#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-eclipse-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  pipelineRef:
    name: eclipse-repo-build
  serviceAccountName: build-bot
  resources:
  - name: git-eclipse
    resourceRef:
      name: git-eclipse-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
